version: '3.8'

services:
  weather-app:
    image: chethan0907/sde-django-weather-app
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    restart: unless-stopped
    container_name: django-weather-app
    
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
